
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./.env.${ENV}
    environment:
      # App settings
      DEBUG: "True"
      LOG_LEVEL: "INFO"
    volumes:
      - .:/app/backend 
      
      # Add other vars as needed
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Linux compatibility