services:
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    #image: timescale-pgvector:pg17
    container_name: automana-postgres-dev
    env_file:
      - ../config/env/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ../infra/db/init/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_dev -d manaforge_dev"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
            - app-network
  backend:
    build:
      context: ..
      dockerfile: deploy/docker/backend/Backend.Dockerfile
    container_name: automana-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
    env_file:
      - ../config/env/.env.dev
    environment:
      - ENV=dev
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
    container_name: automana-nginx-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/certs:/etc/nginx/certs:ro
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  pgdata-dev: