services:
  postgres:
    build:
      context: ..
      dockerfile: deploy/docker/postgres/Dockerfile
    secrets:
        - admin_db_password
        - agent_db_password
        - readonly_db_password
        - backend_db_password
        - celery_db_password
    image: timescale-pgvector:pg17
    container_name: automana-postgres-dev
    env_file:
      - ../config/env/.env.dev
    environment:
      POSTGRES_USER: ${APP_ADMIN_DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/admin_db_password
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
      - ../infra/db/init/:/docker-entrypoint-initdb.d/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_ADMIN_DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
            - backend-network

  backend:
    build:
      context: ..
      dockerfile: deploy/docker/backend/Backend.Dockerfile
    secrets:
        - backend_db_password
        - readonly_db_password
        - encryption_key
        - jwt_secret_key
        - pgp_secret_key 
    container_name: automana-backend-dev
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app/backend
      - ../staging:/app/staging
    env_file:
      - ../config/env/.env.dev
    environment:
      ENV: dev
      POSTGRES_USER: ${APP_BACKEND_DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/backend_db_password
      MODULES_NAMESPACE: backend
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
  proxy:
    build:
      context: ./docker/nginx
      dockerfile: nginx.Dockerfile
      args:
        NGINX_CONF: nginx.local.conf
    container_name: automana-proxy-dev
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../config/nginx/certs:/etc/nginx/certs:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - backend
  redis:
    image: redis:7.0-alpine
    container_name: automana-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
      - redis-config-dev:/usr/local/etc/redis
    networks:
      - backend-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  celery-worker:
    build:
      context: ..
      dockerfile: deploy/docker/celery/celery.Dockerfile
    volumes:
      - "G:/data/scryfall:/data/scryfall"
    secrets:
      - celery_db_password
    container_name: automana-celery-dev
    env_file:
      - ../config/env/.env.dev
    environment:
      POSTGRES_USER: ${APP_CELERY_DB_USER}
      POSTGRES_PASSWORD_FILE: /run/secrets/celery_db_password
      CELERY_CONCURRENCY: "4"
      CELERY_LOGLEVEL: "INFO"
      CELERY_POOL: "prefork"
      MODULES_NAMESPACE: celery
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_healthy
    networks:
      - backend-network
    command: >
      sh -c "celery -A celery_app.main.celery_app worker
      --loglevel=${CELERY_LOGLEVEL:-INFO}
      --concurrency=${CELERY_CONCURRENCY:-4}"
    healthcheck:
      test: ["CMD-SHELL", "celery -A celery_app.main.tasks inspect ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
  celery-beat:
    build:
      context: ..
      dockerfile: deploy/docker/celery/celery.Dockerfile
    secrets:
      - celery_db_password
    container_name: automana-celery-beat-dev
    env_file:
      - ../config/env/.env.dev
    environment:
      CELERY_CONCURRENCY: "4"
      CELERY_LOGLEVEL: "INFO"
      CELERY_POOL: "prefork"
      MODULES_NAMESPACE: celery
    depends_on:
      postgres:
          condition: service_healthy
      redis:
          condition: service_healthy
    command: >
      sh -c "celery -A celery_app.main.celery_app worker
      --loglevel=${CELERY_LOGLEVEL:-INFO}
      --concurrency=${CELERY_CONCURRENCY:-4}"
    networks:
      - backend-network
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f 'celery beat' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
secrets:
  backend_db_password:
    file: ../config/secrets/backend_db_password.txt
  celery_db_password:
    file: ../config/secrets/celery_db_password.txt
  agent_db_password:
    file: ../config/secrets/agent_db_password.txt
  readonly_db_password:
    file: ../config/secrets/readonly_db_password.txt
  admin_db_password:
    file: ../config/secrets/admin_db_password.txt
  openai_api_key:
    file: ../config/secrets/openai_api_key.txt
  jwt_secret_key:
    file: ../config/secrets/jwt_secret_key.txt
  encryption_key:
    file: ../config/secrets/encryption_key.txt
  pgp_secret_key:
    file: ../config/secrets/pgp_secret_key.txt
  tavily_api_key:
    file: ../config/secrets/tavily_api_key.txt
  
networks:
  frontend-network:  # nginx <-> backend
    driver: bridge
  backend-network:   # backend <-> postgres
    driver: bridge
volumes:
  pgdata-dev:
  redis-data-dev:
  redis-config-dev: